@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"E:\stm8\common\bin\cspybat" "E:\stm8\stm8\bin\stm8proc.dll" "E:\stm8\stm8\bin\stm8stlink.dll"  %1 --plugin "E:\stm8\stm8\bin\stm8bat.dll" --backend -B "-p" "E:\stm8\stm8\config\ddf\iostm8s207c8.ddf" "-d" "stlink" "--mcuname" "STM8S207C8" "--verify_download" 


